services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./backend/users.json:/app/backend/users.json
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:8000"
